### ISSUE TITLE
Improve "close channels" screen

### ISSUE THREAD

**Issue by dpad85** [ACINQ/phoenix-kmm#113]
- [x] The input field should accept Bitcoin URIs (such as `bitcoin:XXXXX`)
- [X] Channels not in `NORMAL` state cannot be closed and should not be listed. So if I have 1 `SYNCING` or `OFFLINE` channel, the screen should read "You currently don't have any channels than can be closed etc.."
- [ ] If one (or more) close fails (can happen even if the channel is normal), then the UI should somehow tells it.
- [x] Should be able to scan a QR code from this screen

**Comment by robbiehanson** [comment]
Remaining task is low priority, and has been moved to its own issue: #194
