### ISSUE TITLE
Transaction details screen

### ISSUE THREAD

**Issue by robbiehanson** [ACINQ/phoenix-kmm#122]
When viewing a transaction, (i.e. tap on transaction, and sheet slides up to reveal transaction details):

- the main sheet should show high-level information (i.e. information that's relevant for a non-technical user)
- there should be an option to display advanced information, possibly in another view

This advanced-information screen is missing.

**Comment by dpad85** [comment]
Also the payment hash should be easily to copy to the clipboard (for debugging).

**Comment by robbiehanson** [comment]
Done in 7904d77d4cc32fc314a6cdf010afaf3d916a5d83
