### ISSUE TITLE
Check that a payment has not already been paid before sending

### ISSUE THREAD

**Issue by dpad85** [ACINQ/phoenix-kmm#136]
If the wallet has already sent funds for a payment hash, the wallet should refuse to send new payments for this payment hash.

This could also be checked by the trampoline node, in case the wallet has deleted its local payments database, as a protection against preimage interception by opportunistic nodes on the route.

**Comment by robbiehanson** [comment]
Related issue: https://github.com/ACINQ/lightning-kmp/pull/257
