### ISSUE TITLE
Channel funding transaction link is broken

### ISSUE THREAD

**Issue by robbiehanson** [ACINQ/phoenix-kmm#153]
In Settings -> Channels -> Tap a Channel -> Tap "Tx" button

**Comment by robbiehanson** [comment]
The url is coming from `AppChannelsConfigurationController.kt`:

```kotlin
it.map { (id, state) ->
  ChannelsConfiguration.Model.Channel(
    // ...
    txUrl = if (state is ChannelStateWithCommitments) {
      val prefix = when (chain) {
        Chain.Mainnet -> ""
        Chain.Testnet -> "testnet/"
        Chain.Regtest -> "_REGTEST_/"
      }
      val txId = state.commitments.localCommit.publishableTxs.commitTx.tx.txid
      "https://blockstream.info/$prefix/tx/$txId"
    } else null
  )
}
```

There's the obvious problem with the extra slash for mainnet. But more importantly, the `txId` appears to be invalid. It doesn't work for any of my channels. Neither those funded via SwapIn, nor those funded via Lightning.

**Comment by dpad85** [comment]
We should use `state.commitments.commitInput.outPoint.txId` for the funding tx id.
