### ISSUE TITLE
Get rid of bintray repositories

### ISSUE THREAD

**Issue by sstone** [ACINQ/phoenix-kmm#157]
Once https://github.com/ACINQ/lightning-kmp/pull/231 has been merged we'll have to update phoenix-kmm.
It's not urgent but still need to be done before the 30 April 2021 deadline (see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

**Comment by dpad85** [comment]
For kotlin 1.4.31 we should be good, phoenix-kmm already uses that version.

**Comment by sstone** [comment]
Nice! So we just need to remove bintray repositories from our build file, I'll edit the issue

**Comment by dpad85** [comment]
Should be fixed by #117
