### ISSUE TITLE
Slow performance of kotlinx deserialization

### ISSUE THREAD

**Issue by robbiehanson** [ACINQ/phoenix-kmm#163]
The sqlite routines we're currently using to read & deserialize data from disk are horribly slow. For example, on an iPhone 7, with only 26 rows in the database, here are sample execution times:
```
[SqlitePaymentsDb] listPayments: elapsed: 5558 milliseconds
[SqlitePaymentsDb] listPayments: elapsed: 7078 milliseconds
[SqlitePaymentsDb] listPayments: elapsed: 6334 milliseconds
```

The good news is that, the problem is not the underlying sqlite reads. If I perform the same requests, but remove the `::allPaymentsMapper`, then I get sample execution times:

```
[SqlitePaymentsDb] altListPayments: elapsed: 25 milliseconds
[SqlitePaymentsDb] altListPayments: elapsed: 133 milliseconds
```

The performance of `listLocalChannels` is also a problem. Running the code on an iPhone 7, before we introduced new channel serialization:

```
with 4 channels: [SqliteChannelsDb] listLocalChannels: elapsed: 8996 milliseconds
with 2 channels: [SqliteChannelsDb] listLocalChannels: elapsed: 4893 milliseconds
```

With the new channel serialization code in place:

```
with 2 channels: [SqliteChannelsDb] listLocalChannels: elapsed: 3383 milliseconds
```

**Comment by sstone** [comment]
I've run simple benchmarks (not on iOS/macOS yet though) and there are no significant differences between the old (v1) and new (v2) serialisation  formats. Can you reproduce this pb on the iOS emulator ?

**Comment by robbiehanson** [comment]
> kotlin native serialisation (i.e compiled kotlin code) is about 10x slower on linux (ubuntu) that it is on the JVM, and it seems that it's 10x slower on iOS than it is on ubuntu

The native serialization definitely seems slow. At least the JVM serialization is fast, so perhaps this is something that is fixed with a newer version of Kotlin or the kotlinx serialization library.

I'm not yet sure if it's slower on iOS, or perhaps just that the iPhone 8 hardware is slow. I'm going to borrow an iPhone 12 momentarily to run a few tests.

**Comment by sstone** [comment]
Yes it should improve a bit with kotlin 1.5.0 which should be ready very soon. I also use a second-hand iPhone 8 and never noticed that the app was slow to launch ? 
Here we cannot use native libraries as we did for crypto algorithms, but we could use hand-crafted serialisers instead of relying on kotlinx-serialization (this is what we did for LN and Bitcoin serialisation), but it would be quite tedious and I'll run some tests first to see if it's worth it.

**Comment by sstone** [comment]
I think that the payment db is using the old v1 serialisation format (because it's more user friendly: binary fields are serialised as hex strings), if so switching to the new v2 format should help.

**Comment by robbiehanson** [comment]
I just recompiled the project using Release build, and I'm seeing a huge difference in performance. Sample runs, on the same iPhone 7, with the same database:
```
[SqlitePaymentsDb] listPayments: elapsed: 497 milliseconds
[SqlitePaymentsDb] listPayments: elapsed: 530 milliseconds
```

This is very surprising to me, but good news. I would still consider the serialization slow (the raw db reads were 9 milliseconds & 53 milliseconds), however it's much more manageable now. We have at least 3 things we can do to speed up the app:

- optimize the db reads, by only reading the ordered uuid list on iOS
- upgrade to kotlin 1.5 (and/or latest kotlinx-serialization) at some point
- optionally switch to the new v2 format

If we perform the first 2 optimizations, it can guide our decisions on the 3rd option. (And other more extreme options.)

**Comment by dpad85** [comment]
There is no v2 format for payments serialization.

Regarding the `listPayments` query fetching all the payments from database, it should not do any deserialization (we should only look at the "type_version" field which is a string mapped to an enum, so pretty fast). However [that is not what's done ](https://github.com/ACINQ/phoenix-kmm/blob/e5ddd2ca3b7b378eb4b75a35319ac0a34b095ceb/phoenix-shared/src/commonMain/kotlin/fr.acinq.phoenix/db/SqlitePaymentsDb.kt#L209-L233), we actually deserialize everything :

- `outgoing_status_blob` 
- `outgoing_details_blob`
- `incoming_origin_blob`
- `incoming_received_with_blob`
- a `PublicKey` is created from the `outgoing_recipient`

Those fields should only be retrieved and deserialized when the user opens the details screen of a payment.

So this query should be optimized and read as little info as possible (amount, timestamp, description and status). As mentioned by @robbiehanson, this query could even only provide an ordered uuid list, and then for each displayed row, query the database to get the payment details. Not sure which solution is better.

**Comment by robbiehanson** [comment]
Closing issue. Will create a new issue for performance optimization idea.
