### ISSUE TITLE
Phoenix should auto-detect lightning invoices in clipboard

### ISSUE THREAD

**Issue by robbiehanson** [ACINQ/phoenix-kmm#183]
If you launch Phoenix (or return to the app), and there is a lightning invoice in the clipboard, then Phoenix should ask the user if they want to pay it.

Exception: if the invoice sends a payment to the current wallet

**Comment by dpad85** [comment]
We must make sure that this feature is not obnoxious otherwise it's better not to have it. We should display a discreet message that fades after 5 or 10s and that does not block navigation/important section of the app. The Wallet of Satoshi app has a nice implementation (on Android at least).
