### ISSUE TITLE
Dark Mode compatibility on iOS

### ISSUE THREAD

**Issue by mrcoolbp** [ACINQ/phoenix-kmm#186]
Darkmode on iOS when enabled affects how app look system-wide, when dark mode is enabled the text in Phoenix becomes white but the background does not switch to a dark color, so text is white on white making it almost unreadable.

example:
![image](https://user-images.githubusercontent.com/6710866/125780999-bd8275cb-bc98-4dcf-859d-063240c78d58.png)

Phoenix ver. 1.0.0
iOS ver. 14.6

**Comment by robbiehanson** [comment]
We have been trying to reproduce this issue, but have been unsuccessful so far. The app already supports dark mode. This is what we're seeing on our devices:

<img src="https://user-images.githubusercontent.com/304604/125817399-128b5b3f-07fd-4c7e-93b9-698ef27e02b4.PNG" width="175px"/>

<img src="https://user-images.githubusercontent.com/304604/125818525-7e188d3d-3d24-47a8-b8a8-63c9ce45bb99.PNG" width="175px"/>

<img src="https://user-images.githubusercontent.com/304604/125818733-5c6b589a-222c-4e0e-b66d-c78cfab657b3.PNG" width="175px"/>

- Which device are you using ?
- Are you still experiencing the problem ?
- Did the problem exist throughout the app, or only on the Introduction screens ?

**Comment by robbiehanson** [comment]
Nevermind, we have reproduced this issue. You have "Increase Contrast" enabled in iOS Settings.
