### ISSUE TITLE
Display min funding amount when there are no channels

### ISSUE THREAD

**Issue by dpad85** [ACINQ/phoenix-kmm#190]
Opening a new channel only happens if the amount to be received is above a given threshold (10k sat typically). The UI should show that information when we are sure a new channel has to be created to receive the payment (e.g there are no channels).

This is what we have on Android:

![unnamed](https://user-images.githubusercontent.com/5765435/127140926-e18bc2f3-d5f2-4470-af1a-3a624610e37c.png)

**Comment by robbiehanson** [comment]
<img width="225" alt="Screen Shot 2021-08-02 at 11 48 33" src="https://user-images.githubusercontent.com/304604/127896381-430cb766-9af1-49bb-84e6-d2011044c884.png">
