### ISSUE TITLE
Add support for PYG

### ISSUE THREAD

**Issue by jooray** [ACINQ/phoenix-kmm#204]
I am introducing Lightning with Phoenix in Paraguay, but we have a problem that Phoenix does not support Paraguayan Guaraní (PYG) as a currency. Could you please add it?

Tried on iOS, I don't know if you support it on Android, but that would be very welcome too.

Thank you.

**Comment by dpad85** [comment]
Will do :) we are reworking the Android app to use the phoenix-kmm stack shared with iOS so it will be a good opportunity to support additional currencies.

**Comment by Ventura94** [comment]
It would be equally great if they increased the Cuban peso with its real rate, as explained in yadio.io

**Comment by robbiehanson** [comment]
@Ventura94 Thank you! I had no idea the rate for CUP was inaccurate. In the iOS app we currently support the Argentine Peso via "ARS (official)" & "ARS (blue market)". Is this a similar situation with Cuban Peso, with an "official" exchange rate, and a different free-market rate? Or is the current exchange rate for CUP simply inaccurate?

Dev notes:
Could use this [API](https://api.yadio.io/exrates/USD) to fetch a more accurate USD/CUP rate (more currencies available too).
For context, the currently stated rates are:
- CoinDesk API: 1 USD = 25.75 CUP
- Yadio API: 1 USD = 185 CUP

**Comment by Ventura94** [comment]
[@](https://github.com/robbiehanson) Cuba is in the same situation as Argentina, it has an "official" exchange rate and a different free market rate.

**Comment by dpad85** [comment]
This repository is obsolete and is replaced by https://github.com/ACINQ/phoenix. Please continue the discussion about this issue there.
