### ISSUE TITLE
I made a Czech localization

### ISSUE THREAD

**Issue by Chuck3CZ** [ACINQ/phoenix-kmm#205]
Hi there, I just made a Czech localization  based on _**es.lproj**_ files:

- Localizable.strings
- InfoPlist.strings

Is possible to add translation for future testing ? (TestFlight or beta testing somehow) I would like to help with it.

> GitHub Link: https://github.com/Chuck3CZ/phoenix-kmm-Phoenix-CS-CZ
>
> Release: https://github.com/Chuck3CZ/phoenix-kmm-Phoenix-CS-CZ/releases

Thanks, and have a nice day ☺

**Comment by robbiehanson** [comment]
Looking good ! We are getting ready to push out a TestFlight build for you.

<img width="250" alt="Screen Shot 2021-09-13 at 08 22 32" src="https://user-images.githubusercontent.com/304604/133091962-42fbbcba-2900-482e-961c-da6bac6d850e.png">

There are 2 hidden localized HTML files that are easy to miss [here](https://github.com/ACINQ/phoenix-kmm/tree/czech-localization/phoenix-ios/phoenix-ios/views/html/cs.lproj)

- about.html - Displayed via: Settings -> About
- advancedSecurity.html - Displayed via: Settings -> App Access -> Question Button (?)

**Comment by Chuck3CZ** [comment]
Thanks for reply. I just finished these html files in new release: https://github.com/Chuck3CZ/phoenix-kmm-Phoenix-CS-CZ/releases/tag/Czech_Html

- about.html https://github.com/Chuck3CZ/phoenix-kmm-Phoenix-CS-CZ/blob/main/about.html

- advancedSecurity.html https://github.com/Chuck3CZ/phoenix-kmm-Phoenix-CS-CZ/blob/main/advancedSecurity.html

**Comment by Chuck3CZ** [comment]
I hope it works and It is all for now. ☺

**Comment by robbiehanson** [comment]
Sorry for the lack of updates. There is currently a TestFlight build available with your localization. (If you don't already have access to our TestFlight beta builds, you can send us an email at phoenix@acinq.co)

The build doesn't have your changes to `about.html` & `advancedSecurity.html`. But we are planning on putting out another build very soon (probably this week), which should include those files.

**Comment by dpad85** [comment]
Html files have been pushed to phoenix (https://github.com/ACINQ/phoenix/commit/2cc741b0e883c4c6be24b5874baecee20b0b4d55). Thanks!

**Comment by robbiehanson** [comment]
Phoenix iOS version 1.1.2 has been release to App Store with Czech localization. Thanks again !!

Note that we've merged phoenix-kmm into the phoenix repo. (_We are working on migrating the Android version to the shared Kotlin library, so both the iOS & Android apps have a shared codebase._) So if you need to make future changes, you can do so [here](https://github.com/ACINQ/phoenix/pulls).
